import Nav from "@/components/nav";
import { Toaster } from "react-hot-toast";
import "./globals.css";

export const metadata = {
  title: "Junayed | Web Developer",
  // description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className="bg-slate-900 text-slate-400 font-primary">
        <Nav />
        {children}
        <Toaster />
      </body>
    </html>
  );
}
